language: android
jdk: oraclejdk8
env:
  matrix:
    - KSTOREPWD="Duitsland" KEYPWD="Duitsland"
android:
  components:
    - platform-tools
    - build-tools-27.0.3
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository

script:
   - ./gradlew build connectedCheck
